name: Ubuntu 20.04

# Dependencies of this package
env:
  UBUNTU_APT: ${{ 'libpango1.0-dev gir1.2-pango-1.0 libcairo2-dev libcairo-gobject2 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # Ubuntu 20.04 tasks
  build-ubuntu-20_04-swift-latest:
    runs-on: ubuntu-20.04
    steps:
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@v1
        with:
          swift-version: '5.6.1'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftPangoCairo
        uses: actions/checkout@v2
        with:
          path: SwiftPangoCairo

      - name: Build SwiftPangoCairo
        run: |
          cd SwiftPangoCairo
          swift build
          cd ..

      - name: Test SwiftPangoCairo
        run: |
          cd SwiftPangoCairo
          swift test
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftPangoCairo
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artefact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artefact-20.04-5.3
          path: |
            SwiftPangoCairo/Sources/
          retention-days: 1
